version: '3.8'
services:
  postgres:
    image: postgres:14-alpine
    container_name: blogapi-postgres
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=blogapi
    networks:
      - blogapi-network
networks:
  blogapi-network:
    name: blogapi-network
    driver: bridge
